language: python
sudo: false
python:
  - "2.7"

#command to install dependencies
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install coveralls

script:
  - flake8 

after_success: coveralls

notifications:
  email:
    on_success: change
    on_failure: always

